{
 "title": "go-server dashboard",
 "description": "Logs and metrics",
 "tags": [
  "loki",
  "promtail",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "label_values(job)" },
   { "name": "search", "label": "String Match" }
  ]
 },
 "panels": [
  {
   "title": "http get requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "echo_http_requests_total{method=\"GET\", job=\"go-echo-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "updates",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$app\"} |= \"$search\" [$__interval]))"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"go-echo-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "app logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker-logs\", image_name=\"go-server-practice_backend\"} | json | line_format \"{{.log}}\" |~ `\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2}:\\d{2}`"
    }
   ]
  }
 ]
}