name: CI

on: 
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: '1.24'

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

  lint-code:
    needs: go-mod-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
  
  publish-image:
    needs: lint-code
    if: github.ref == "refs/heads/main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build image
        run: docker build . -t ${{ secrets.DOCKER_HUB_NAME }}/go-server-practice_backend:latest
      - name: push image to docker hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_NAME }} --password-stdin
          docker push ${{ secrets.DOCKER_HUB_NAME }}/go-server-practice_backend:latest